name: Directory submission
description: Submit a new directory to be added to the list
title: "[SUBMISSION] "
labels: submission
assignees: 'submitdirectories'

body:
- type: markdown
  attributes:
    value: |
      Thanks for contributing a new directory! Please provide the details below.

- type: input
  id: category
  attributes:
    label: Category
    description: "Category of the directory (e.g., AI Tool, SaaS, etc.)."
    placeholder: "Enter the category"
  validations:
    required: true

- type: input
  id: submission_type
  attributes:
    label: Submission Type
    description: "Type of submission (e.g., Free, Paid, Sign In)."
    placeholder: "Free"
  validations:
    required: true

- type: input
  id: domain_authority
  attributes:
    label: Domain Authority (DA)
    description: "Domain Authority of the directory website."
    placeholder: "e.g., 45"
  validations:
    required: true

- type: input
  id: website_url
  attributes:
    label: Website URL
    description: "URL of the directory website."
    placeholder: "https://example.com"
  validations:
    required: true

- type: input
  id: submit_url
  attributes:
    label: Submit URL
    description: "URL where users can submit their website."
    placeholder: "https://example.com/submit"
  validations:
    required: true
