name: Feature request
description: Suggest a new feature or enhancement for SubmitDirectories
title: "[FEATURE] "
labels: enhancement
assignees: 'submitdirectories'

body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to suggest a feature! Please provide as much detail as possible to help us understand your idea.

- type: textarea
  id: description
  attributes:
    label: Description
    description: A clear and concise description of the feature.
    placeholder: "Please describe the feature..."
  validations:
    required: true

- type: textarea
  id: motivation
  attributes:
    label: Motivation
    description: "Please describe the problem you are trying to solve."
    placeholder: "What problem does this feature address?"
  validations:
    required: true

- type: textarea
  id: solution
  attributes:
    label: Proposed Solution
    description: "Describe the solution you'd like to see."
    placeholder: "How do you think the feature should work?"
  validations:
    required: true
